version: '3'

services:
    db:
        restart: always
        image: "postgres:9.6"
    web:
        build: ./teoscrap
        volumes:
            - ./teoscrap/src:/srv/src
        ports:
            - 8080:8080
        depends_on:
            - db
        command: ["/wait-for-postgres.sh", "db 5432", "/entrypoint.sh"]

