# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170502_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='articleword',
            name='words_number',
            field=models.PositiveIntegerField(),
        ),
    ]
